import { useCallback, useState } from "react";
import "./styles/tokens.css";
import "./styles/primitives.css";
import { useRoomState, useRoomDispatch } from "../state/RoomStateContext";
import { useRoomSocket } from "../hooks/useRoomSocket";
import { useViewportHeight } from "../hooks/useViewportHeight";
import type { ServerState } from "../state/types";
import { Join } from "./screens/Join";
import { V2Terminal } from "./V2Terminal";

// Seed rooms get an autogenerated code so a tester never collides with a real
// game. Ambiguous glyphs (0/O/1/I) are excluded.
function randomSeedCode(n = 4): string {
  const A = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let s = "";
  for (let i = 0; i < n; i++) s += A[Math.floor(Math.random() * A.length)];
  return `SEED-${s}`;
}

export default function V2App() {
  const { session } = useRoomState();
  const dispatch = useRoomDispatch();
  const [joinError, setJoinError] = useState("");
  useViewportHeight();

  const applyState = useCallback(
    (state: ServerState) => dispatch({ type: "applyServerState", state }),
    [dispatch],
  );
  useRoomSocket(session, applyState);

  const onJoin = useCallback(async (room: string, name: string, side: string) => {
    setJoinError("");
    try {
      const resp = await fetch(`/api/game/${encodeURIComponent(room)}/join`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, side }),
      });
      if (!resp.ok) throw new Error(`join failed (${resp.status})`);
      const data = await resp.json();
      if (!data.side) throw new Error("Room is full.");
      dispatch({ type: "setSession", session: { room, side: data.side, name } });
      dispatch({ type: "applyServerState", state: data.state });
    } catch (e) {
      setJoinError(e instanceof Error ? e.message : "Join failed");
    }
  }, [dispatch]);

  const onSeed = useCallback(async (first: "a" | "b") => {
    setJoinError("");
    const room = randomSeedCode();
    try {
      const jr = await fetch(`/api/game/${encodeURIComponent(room)}/join`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ side: "a" }),
      });
      if (!jr.ok) throw new Error(`seed join failed (${jr.status})`);
      const jd = await jr.json();
      dispatch({ type: "setSession", session: { room, side: jd.side, name: "Tester" } });
      const cr = await fetch(`/api/game/${encodeURIComponent(room)}/command`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ cmd: { verb: "seed", attrs: { first } }, side: "a" }),
      });
      if (!cr.ok) throw new Error(`seed failed (${cr.status})`);
      const cd = await cr.json();
      dispatch({ type: "applyServerState", state: cd.state });
    } catch (e) {
      setJoinError(e instanceof Error ? e.message : "Seed failed");
    }
  }, [dispatch]);

  if (!session?.room) return <Join onJoin={onJoin} error={joinError} onSeed={onSeed} />;
  return <V2Terminal />;
}
